// Mock data for the admin dashboard

export const mockUsers = [
  {
    id: "1",
    fullName: "John Smith",
    email: "john.smith@example.com",
    phone: "+1-555-0101",
    age: 32,
    gender: "Male",
    city: "New York",
    province: "NY",
    country: "USA",
    role: "Customer",
    status: "Verified",
    dateJoined: new Date("2023-01-15"),
  },
  {
    id: "2",
    fullName: "Sarah Johnson",
    email: "sarah.j@example.com",
    phone: "+1-555-0102",
    age: 28,
    gender: "Female",
    city: "Los Angeles",
    province: "CA",
    country: "USA",
    role: "CarOwner",
    status: "Verified",
    dateJoined: new Date("2023-03-20"),
  },
  {
    id: "3",
    fullName: "Michael Chen",
    email: "m.chen@example.com",
    phone: "+1-555-0103",
    age: 45,
    gender: "Male",
    city: "Chicago",
    province: "IL",
    country: "USA",
    role: "Customer",
    status: "Verified",
    dateJoined: new Date("2023-05-10"),
  },
  {
    id: "4",
    fullName: "Emily Davis",
    email: "emily.d@example.com",
    phone: "+1-555-0104",
    age: 35,
    gender: "Female",
    city: "Houston",
    province: "TX",
    country: "USA",
    role: "Customer",
    status: "Unverified",
    dateJoined: new Date("2024-01-05"),
  },
  {
    id: "5",
    fullName: "Robert Wilson",
    email: "r.wilson@example.com",
    phone: "+1-555-0105",
    age: 52,
    gender: "Male",
    city: "Phoenix",
    province: "AZ",
    country: "USA",
    role: "CarOwner",
    status: "Verified",
    dateJoined: new Date("2022-11-30"),
  },
]

export const mockCars = [
  {
    id: "1",
    ownerId: "2",
    name: "Tesla Model 3",
    price: 85,
    carDetails: {
      seats: 5,
      transmission: "Automatic",
      fuelType: "Electric",
      plateNumber: "TSL-2024-001",
    },
    rating: 4.8,
    image: "/tesla-model-3.png",
    status: "Available",
    createdAt: new Date("2023-06-01"),
  },
  {
    id: "2",
    ownerId: "2",
    name: "BMW X5",
    price: 120,
    carDetails: {
      seats: 7,
      transmission: "Automatic",
      fuelType: "Gasoline",
      plateNumber: "BMW-2024-002",
    },
    rating: 4.6,
    image: "/bmw-x5-suv.png",
    status: "Available",
    createdAt: new Date("2023-07-15"),
  },
  {
    id: "3",
    ownerId: "5",
    name: "Honda Civic",
    price: 55,
    carDetails: {
      seats: 5,
      transmission: "Manual",
      fuelType: "Gasoline",
      plateNumber: "HND-2024-003",
    },
    rating: 4.4,
    image: "/honda-civic-modern-city.png",
    status: "Available",
    createdAt: new Date("2023-08-20"),
  },
  {
    id: "4",
    ownerId: "5",
    name: "Mercedes-Benz C-Class",
    price: 150,
    carDetails: {
      seats: 5,
      transmission: "Automatic",
      fuelType: "Gasoline",
      plateNumber: "MBZ-2024-004",
    },
    rating: 4.9,
    image: "/mercedes-benz-c-class.jpg",
    status: "Unavailable",
    createdAt: new Date("2023-09-10"),
  },
  {
    id: "5",
    ownerId: "2",
    name: "Toyota Camry",
    price: 65,
    carDetails: {
      seats: 5,
      transmission: "Automatic",
      fuelType: "Hybrid",
      plateNumber: "TOY-2024-005",
    },
    rating: 4.5,
    image: "/toyota-camry-modern.png",
    status: "Available",
    createdAt: new Date("2023-10-05"),
  },
]

export const mockBookings = [
  {
    id: "1",
    ownerId: "2",
    customerId: "1",
    carId: "1",
    pickupDate: new Date("2024-10-20"),
    returnDate: new Date("2024-10-25"),
    totalPrice: 425,
    status: "Confirmed",
    createdAt: new Date("2024-10-18"),
  },
  {
    id: "2",
    ownerId: "5",
    customerId: "3",
    carId: "3",
    pickupDate: new Date("2024-10-22"),
    returnDate: new Date("2024-10-24"),
    totalPrice: 110,
    status: "Pending",
    createdAt: new Date("2024-10-19"),
  },
  {
    id: "3",
    ownerId: "2",
    customerId: "4",
    carId: "2",
    pickupDate: new Date("2024-10-25"),
    returnDate: new Date("2024-10-28"),
    totalPrice: 360,
    status: "Confirmed",
    createdAt: new Date("2024-10-17"),
  },
  {
    id: "4",
    ownerId: "5",
    customerId: "1",
    carId: "4",
    pickupDate: new Date("2024-11-01"),
    returnDate: new Date("2024-11-05"),
    totalPrice: 600,
    status: "Pending",
    createdAt: new Date("2024-10-19"),
  },
  {
    id: "5",
    ownerId: "2",
    customerId: "3",
    carId: "5",
    pickupDate: new Date("2024-10-21"),
    returnDate: new Date("2024-10-23"),
    totalPrice: 130,
    status: "Completed",
    createdAt: new Date("2024-10-15"),
  },
]

// Mock car owner applications data
export const mockCarOwnerApplications = [
  {
    id: "APP-001",
    userId: "1",
    userName: "John Smith",
    userEmail: "john.smith@example.com",
    businessName: "Smith Car Rentals",
    businessAddress: "123 Main St, New York, NY 10001",
    businessPhone: "+1-555-0101",
    businessEmail: "business@smithrentals.com",
    taxId: "12-3456789",
    drivingLicense: "/sample-license.jpg",
    businessLicense: "/sample-business-license.jpg",
    description: "Experienced car rental business with 5+ years in the industry. Professional fleet management.",
    status: "Pending",
    adminNotes: null,
    reviewedBy: null,
    reviewedAt: null,
    createdAt: new Date("2024-10-15"),
  },
  {
    id: "APP-002",
    userId: "3",
    userName: "Michael Chen",
    userEmail: "m.chen@example.com",
    businessName: "Chen Premium Vehicles",
    businessAddress: "456 Oak Ave, Chicago, IL 60601",
    businessPhone: "+1-555-0103",
    businessEmail: "info@chenpremium.com",
    taxId: "98-7654321",
    drivingLicense: "/sample-license.jpg",
    businessLicense: "/sample-business-license.jpg",
    description: "Luxury car rental service focusing on premium and exotic vehicles.",
    status: "Approved",
    adminNotes: "Verified business registration and insurance coverage. Approved for operations.",
    reviewedBy: "ADMIN-001",
    reviewedAt: new Date("2024-10-17"),
    createdAt: new Date("2024-10-10"),
  },
  {
    id: "APP-003",
    userId: "4",
    userName: "Emily Davis",
    userEmail: "emily.d@example.com",
    businessName: "Davis Urban Mobility",
    businessAddress: "789 Elm Rd, Houston, TX 77001",
    businessPhone: "+1-555-0104",
    businessEmail: "admin@davisurbantransit.com",
    taxId: "55-1122334",
    drivingLicense: "/sample-license.jpg",
    businessLicense: "/sample-business-license.jpg",
    description: "Urban mobility solutions with eco-friendly vehicles.",
    status: "Rejected",
    adminNotes: "Tax ID verification failed. Business license expired. Please reapply with valid documents.",
    reviewedBy: "ADMIN-002",
    reviewedAt: new Date("2024-10-16"),
    createdAt: new Date("2024-10-08"),
  },
  {
    id: "APP-004",
    userId: "2",
    userName: "Sarah Johnson",
    userEmail: "sarah.j@example.com",
    businessName: "Johnson Fleet Services",
    businessAddress: "321 Pine Ln, Los Angeles, CA 90001",
    businessPhone: "+1-555-0102",
    businessEmail: "fleet@johnsonservices.com",
    taxId: "44-5566778",
    drivingLicense: "/sample-license.jpg",
    businessLicense: "/sample-business-license.jpg",
    description: "Corporate fleet rental and maintenance services.",
    status: "Pending",
    adminNotes: null,
    reviewedBy: null,
    reviewedAt: null,
    createdAt: new Date("2024-10-18"),
  },
  {
    id: "APP-005",
    userId: "5",
    userName: "Robert Wilson",
    userEmail: "r.wilson@example.com",
    businessName: "Wilson Transportation Group",
    businessAddress: "654 Maple Dr, Phoenix, AZ 85001",
    businessPhone: "+1-555-0105",
    businessEmail: "corporate@wilsontransport.com",
    taxId: "77-8899001",
    drivingLicense: "/sample-license.jpg",
    businessLicense: "/sample-business-license.jpg",
    description: "Large-scale transportation and vehicle rental enterprise.",
    status: "Approved",
    adminNotes: "Comprehensive documentation verified. High-capacity operations approved.",
    reviewedBy: "ADMIN-001",
    reviewedAt: new Date("2024-10-14"),
    createdAt: new Date("2024-10-05"),
  },
]
